import re

html = open(r"D:\Project\Farm Postman\recon\signup.html", encoding="utf-8").read()

# input element ids/names
print("=== INPUT DETAILS ===")
for m in re.finditer(r'<input([^>]*)>', html):
    attrs = m.group(1)
    if any(k in attrs for k in ['email', 'username', 'password', 'name', 'id']):
        ids = re.findall(r'(?:id|name)="([^"]+)"', attrs)
        typ = re.search(r'type="([^"]+)"', attrs)
        if ids:
            print(ids, "|type=", typ.group(1) if typ else "?", "|attrs:", attrs[:80])

print("\n=== SUBMIT BUTTON ===")
for m in re.finditer(r'<button[^>]*(?:sign-up-btn|sign-up)[^>]*>', html)[:1] if False else []:
    pass
for m in list(re.finditer(r'id="sign-up-btn"[^>]*>', html))[:1]:
    print(m.group(0))

print("\n=== autogeneratedUsername ===")
i = html.find('autogeneratedUsername')
print(html[max(0,i-150):i+150])

print("\n=== FH: how submit is triggered ===")
# find where onSubmit called / form submit binding
for m in list(re.finditer(r'(?:submit|onSubmit|click)[^;]{0,80}(sign-up-btn|signUpBtn|sign-up-form)[^;]{0,80}', html))[:6]:
    print(m.group(0)[:160])